/* Login Types */
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_START_SUCCESS = 'LOGIN_START_SUCCESS';
export const LOGIN_START_ERROR = 'LOGIN_START_ERROR';
export const SET_LOGIN = 'SET_LOGIN';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_START_SUCCESS = 'REGISTER_START_SUCCESS';
export const REGISTER_START_ERROR = 'REGISTER_START_ERROR';
export const SET_REGISTER = 'SET_REGISTER';
